name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.UPD_SUBMODULE }}
          submodules: true
                    # 'recursive' if necessary
                    # fetch-depth: 0
      
      - name: Update submodules
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git submodule update --remote --recursive
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "update"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "Nothing to update."
          fi
